ALTER TABLE clients
  ADD COLUMN IF NOT EXISTS source        TEXT    NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS tags          TEXT[]  NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS rating        SMALLINT,
  ADD COLUMN IF NOT EXISTS property_type TEXT    NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS property_area TEXT    NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS has_children  BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS has_pets      BOOLEAN NOT NULL DEFAULT FALSE;
